[project]
name = "brazil-unrest-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "nbformat>=5.10.4",
    "plotly[express]>=6.3.1",
    "polars>=1.35.1",
]
